# Generated by Django 5.2.5 on 2025-09-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(default='firma', max_length=100)),
                ('contactname', models.CharField(default='yhteyshenkilo', max_length=100)),
                ('address', models.CharField(default='osoite', max_length=200)),
                ('phone', models.CharField(default='puhelin', max_length=20)),
                ('email', models.EmailField(default='sahkoposti@esimerkki.com', max_length=100)),
                ('country', models.CharField(default='maa', max_length=50)),
            ],
        ),
    ]
