# Generated by Django 5.2.5 on 2025-09-07 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(default='tuote', max_length=100)),
                ('category', models.CharField(default='kategoria', max_length=100)),
                ('quantityperunit', models.CharField(default='kpl', max_length=50)),
                ('unitprice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('unitsinstock', models.IntegerField(default=0)),
                ('unitsonorder', models.IntegerField(default=0)),
                ('reorderlevel', models.IntegerField(default=0)),
                ('discontinued', models.BooleanField(default=False)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.supplier')),
            ],
        ),
    ]
