# Generated by Django 5.2.5 on 2025-09-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discontinued',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantityperunit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reorderlevel',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unitsonorder',
        ),
        migrations.AddField(
            model_name='product',
            name='packagesize',
            field=models.CharField(default=3, max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='productname',
            field=models.CharField(default='laku', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='unitprice',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='unitsinstock',
            field=models.IntegerField(default=3),
        ),
    ]
