# Generated by Django 5.2.5 on 2025-10-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_product_category_remove_product_discontinued_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customername', models.CharField(default='asiakas', max_length=100)),
                ('customerfname', models.CharField(default='etunimi', max_length=50)),
                ('customerlname', models.CharField(default='sukunimi', max_length=50)),
                ('contactname', models.CharField(default='yhteyshenkilo', max_length=100)),
                ('address', models.CharField(default='osoite', max_length=200)),
                ('phone', models.CharField(default='puhelin', max_length=20)),
                ('email', models.EmailField(default='sahkoposti@esimerkki.com', max_length=100)),
            ],
        ),
    ]
