# Generated by Django 5.2.5 on 2025-10-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='contactname',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customername',
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(default='maa', max_length=50),
        ),
    ]
