# Generated by Django 5.2.5 on 2025-11-01 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_customer_contactname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernumber', models.CharField(max_length=20, unique=True)),
                ('customer', models.CharField(max_length=100)),
                ('packagesize', models.CharField(max_length=50)),
                ('unitprice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unitsinstock', models.PositiveIntegerField(default=0)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app.supplier')),
            ],
        ),
    ]
